### ISSUE TITLE
ssh: connect to host ghoster_server.com port 2222: Connection refused

### ISSUE THREAD

**Issue by gustavokei** [peterwilli/Ghoster#3]
Hi, I am unable to use this since I keep getting this error when I run `ssh user@ghoster_server.com -p 2222 -R 0:localhost:3000` (of course with my data).

I have a CentOS 7 server in which I cloned this repo and changed the `config.js` properly.
Docker-compose did setup everything fine, but when I try to run the ssh command on my machine, I get that error.

Any ideas?

**Comment by peterwilli** [comment]
Hi @gustavokei! It's because the ghoster_server.com is a placeholder and I was hoping people would host it themselves. Since multiple people are talking about this now, I will make a demo site (with limits) that ppl can use.

I'm really busy this month but I'll make sure it'll get there!

**Comment by gustavokei** [comment]
Thanks for the response. I did host it myself. I ran `ssh myuser@myserver.com -p 2222 -R 0:localhost:3000`,

I was trying to use this as a self-hosted service. However, I got the error I have mentioned before.
